### PR TITLE
Use notify directly for zip file uploads

### PR DESCRIPTION
**Pull request by nicoandmee**
The problem: Any files over 50MB (for telegram) and a measly 8MB (for discord) do not get uploaded. For me at least, this is an annoyance as I like to be able to review the results from whatever machine I happen to be at.

All this does is use [notify](https://github.com/projectdiscovery/notify) directly rather than parsing out the attributes from the config file. Perhaps there is a reason that is being done that I have not considered. But using this approach and https://transfer.sh/ notify will send out the URL to all the configured receivers once the upload completes. There is no size limit that I am aware of- I am uploading 200-300MB zip files without any issue.

Caveat: File will be deleted after 2 weeks. To me that seems entirely appropriate. Humbly submitted for your @six2dez consideration.

### CODE REVIEW

**Comment by six2dez** [comment]
Hey! Thanks for the PR! I was thinking about the issue and what I will do is detect if the zip file is bigger than 8MB -> then send over transfer.sh, otherwise send over Telegram/Discord/Slack.

If you think you are able to implement this fix then go for it, if not I will do it soon by myself, meanwhile I will keep this PR open :)

**Comment by nicoandmee** [comment]
@six2dez Would love to give it a shot! 👍 Will update this PR when ready in next day or two

**Comment by nicoandmee** [comment]
WDYT @six2dez ? I suppose we could check slack and discord separately since the file upload size limits differ for each, but that feels kinda unnecessary since the transfer.sh link will go to both anyway :thinking:

**Comment by nicoandmee** [comment]
@six2dez I spotted another "issue" that maybe would be worth addressing here- currently the `.zip` is the whole directory tree like, for example: `/home/op/reconftw-data/mysite.com/`. To me this is not idea, I would rather just have the `mysite.com` be at the root of the archive.

To that end I made a [change](https://github.com/six2dez/reconftw/pull/582/commits/6323c27dd3aed17da99ad3aa3e9439affb9e3d93) based on what I read about how zip behaves and [subshells](https://unix.stackexchange.com/questions/138463/do-parentheses-really-put-the-command-in-a-subshell). Confirmed it does seem to work as expected

**Pull request merged**
