### PR TITLE
Optimising the Dockerfile for image size

### PR DESCRIPTION
**Pull request by frost19k**
I've rewritten the Dockerfile with a new syntax (which is compatible with `docker/setup-buildx-action@v1`)

I've streamlined the code therein while introducing some housecleaning steps towards the end.

The result is an image which is 23% smaller than the current build.

```bash
❯ docker images
REPOSITORY              TAG       IMAGE ID       CREATED          SIZE
frost19k/reconftw       latest    d3562dfb3639   19 minutes ago   5.41GB
six2dez/reconftw        main      0912760a2246   4 days ago       7.05GB
```

Note: I have not uninstalled Golang nor the compiled binaries in `~/go/bin`. These binaries are copied to `/usr/local/bin` by `install.sh` so they're a redundant copy & removing them will reduce the image size by another GB and a half.

### CODE REVIEW

**Comment by six2dez** [comment]
Thanks for this PR! Let me a few days to test it properly before merging :)

**Comment by frost19k** [comment]
So, I've been running the `c08f101` commit for a few days now (in `recon` & `subdomain` modes) - without error.

I discovered that Golang needs to be installed for `axiom-configure`, however `/root/go` can be safely removed, as well as `/root/.cache/go` which is just build cache.

Final image is 4.43GB in size, representing a 37% reduction.

**Comment by frost19k** [comment]
So, I've been running the `c08f101` commit for a few days now (in `recon` & `subdomain` modes) - without error.

I discovered that Golang needs to be installed for `axiom-configure`, however `/root/go` can be safely removed, as well as `/root/.cache/go` which is just build cache.

Final image is 4.43GB in size, representing a 37% reduction.

**Comment by six2dez** [comment]
Can you add `sudo` package installation regarding this issue https://github.com/six2dez/reconftw/pull/432? Or at least check it's installed in kali-rolling image (I thought it was by default)

**Comment by frost19k** [comment]
Generally, `sudo` is not installed in any base image. As far as container philosophy is concerned it is "bloat" :-P

We can setup `sudo` inside the container, but we're already `root` so it's sorta redundant & inelegant. Although, from a purely functional POV there are no downsides to doing so.

Personally, I agree with the changes in that commit - but if you wanna go ahead with this it is a really minor change in the Dockerfile. Lemme know.

**Comment by six2dez** [comment]
Ok, thanks for the clarifications, let me improve the code to avoid using `sudo` if we are inside a container, thanks!

**Pull request merged**
