### PR TITLE
mainly formatting and shell optimization

### PR DESCRIPTION
**Pull request by itsgudenuf**
if/then statement clean up & removal of subshells in evaluations.
Code tweaks to allow for better linting in Shellcheck.
Added HTTPX Timeout values.

added some functions for upcoming PRs

### CODE REVIEW

**Comment by six2dez** [comment]
PR changed to dev branch

**Comment by six2dez** [comment]
Plz review the conflicts and resubmit the PR or fix this one

**Comment by itsgudenuf** [comment]
I'll resubmit the PR.  I new something didn't look right when I was submitting it.

Will also break it up into a couple of PRs so it's less likely to conflict.

**Comment by itsgudenuf** [comment]
One more thing.  Should I be cloning from the dev or master branch?

**Comment by six2dez** [comment]
For PR always clone dev branch. Thanks! :)

**Pull request closed without merging**
