### PR TITLE
Use systemwide install if already exist

### PR DESCRIPTION
**Pull request by SkyperTHC**
Changed install.sh to only install packages that are not already installed. Reduces install time and prevents duplication in containered environments.

### CODE REVIEW

**Comment by six2dez** [comment]
This is a good idea, but the one of the goal of the installer is to update the tools to the latest version in order to use latest features and so. With this method probably reconftw will stop working in the right way because of there will missing flags or arguments in the tools. What do you think about this?

**Comment by SkyperTHC** [comment]
You have a valid point, however, I would assume that the systemwide install is always the latest and perhaps add a flag to overwrite the check...such as:

```
USE_LOCAL=1 ./install.sh
```

which would then ignore system wide installs.

or other way around
```
USE_SYSTEM=1 ./install..sh
```

which would then prefer system wide installs.


Otherwise, on systems with many users, the tool becomes ununsuable (because every use installs the entire thing into their home directory...gigabytes of data...when the latest is already installed for all users to use but systemwide)

**Comment by six2dez** [comment]
The best way to solve this I think is adding a new flag to the installer to avoid reinstalling the already installed tools, but keeping the current behavior as default. Could you do this changes? Otherwise I will do

**Comment by six2dez** [comment]
As reconftw always tries to use the latest versions and features of all the tools inside I don't see the point of not updating the tools

**Pull request closed without merging**
